*** Settings ***
Documentation    A test suite with a single Gherkin style test.
Force Tags    robot
Resource    ./login_step_definitions.robot
Metadata    Feature    Login
Metadata    Generated by    _gherkin2robotframework on 2021-05-11T16:17:32.348075_

*** Test Cases ***
Valid Login
    [Tags]    AUTOMATED
    Given browser is opened to login page
    When user "demo" logs in with password "mode"
    Then welcome page should be open


